# -*- coding: utf-8 -*-
# Generated by Django 1.10a1 on 2016-06-10 04:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='areaRegionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='parkingAreas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.IntegerField(default=0)),
                ('filled', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='parkingHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parked_at', models.DateTimeField(auto_now_add=True)),
                ('parked_go', models.DateTimeField(null=True)),
                ('amount', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='parkingRaspberryMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_mappings', to='parking.parkingAreas')),
            ],
        ),
        migrations.CreateModel(
            name='parkingRegions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='raspberry',
            fields=[
                ('raspberry_id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=255, null=True)),
                ('ip', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='raspberryPhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_mac', models.CharField(max_length=255)),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.raspberry')),
            ],
        ),
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('pi_port', models.IntegerField()),
                ('occupied', models.BooleanField(default=False)),
                ('qr', models.CharField(max_length=255, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='parking.raspberry')),
            ],
        ),
        migrations.AddField(
            model_name='parkingraspberrymapping',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pi_mappings', to='parking.raspberry', unique=True),
        ),
        migrations.AddField(
            model_name='parkinghistory',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='parking.sensors'),
        ),
        migrations.AddField(
            model_name='parkinghistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='arearegionmapping',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_mappings', to='parking.parkingAreas'),
        ),
        migrations.AddField(
            model_name='arearegionmapping',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_mappings', to='parking.parkingRegions'),
        ),
        migrations.AlterUniqueTogether(
            name='sensors',
            unique_together=set([('pi', 'pi_port')]),
        ),
        migrations.AlterUniqueTogether(
            name='parkingraspberrymapping',
            unique_together=set([('area', 'pi')]),
        ),
        migrations.AlterUniqueTogether(
            name='arearegionmapping',
            unique_together=set([('region', 'area')]),
        ),
    ]
