# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-05-10 13:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='raspberry',
            fields=[
                ('raspberry_id', models.AutoField(primary_key=True, serialize=False)),
                ('mac', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='raspberryPhone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_mac', models.CharField(max_length=255)),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.raspberry')),
            ],
        ),
        migrations.CreateModel(
            name='sensors',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('pi_port', models.IntegerField()),
                ('occupied', models.BooleanField(default=False)),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parking.raspberry')),
            ],
        ),
        migrations.CreateModel(
            name='spots',
            fields=[
                ('spot_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=15)),
                ('table_name', models.CharField(max_length=255)),
                ('filled', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sensors',
            unique_together=set([('pi', 'pi_port')]),
        ),
    ]
